### ISSUE TITLE
Setup and configure Parse (or similar) server-side data store

### ISSUE THREAD

**Issue by morganwildermuth** [ChangeClothes/ios#5]
Install it and configure it in a way that makes it easy to use (wrapper perhaps?)

**Comment by randyting** [comment]
Yes, I think subclassing PFObject will be the first step - should be really quick and relatively easy to be used by view controllers.  Please take a look branch 'prototypeScheduling'.  I subclassed PFObject for the 'Meeting' class.  I think in addition, we only need a 'User' and 'Image' class.  @mathkellogg Do you agree with this?  Any thoughts on model fields yet?  I took my best guess for the AMRMeeting model to hack my prototype together, but could definitely use your feedback if I'm doing something stupid.

Implementing the PFLoginViewController will give us access to the logged in user and access tokens.  The parse framework should be able to take care of all the authentication for us if we use PFLoginViewController.
